-- phpMyAdmin SQL Dump
-- version 4.6.6deb5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Feb 21, 2020 at 11:34 PM
-- Server version: 5.7.27-0ubuntu0.18.04.1
-- PHP Version: 7.2.24-0ubuntu0.18.04.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `recipebuilder`
--

-- --------------------------------------------------------

--
-- Table structure for table `favoriterecipes`
--

DROP TABLE IF EXISTS `favoriterecipes`;
CREATE TABLE `favoriterecipes` (
  `id` int(55) UNSIGNED NOT NULL,
  `userName` varchar(255) NOT NULL,
  `recipeId` int(55) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `favoriterecipes`
--

INSERT INTO `favoriterecipes` (`id`, `userName`, `recipeId`) VALUES
(226, 'guest', 6),
(231, 'guest', 1),
(232, 'guest', 19);

-- --------------------------------------------------------

--
-- Table structure for table `recipeinstructions`
--

DROP TABLE IF EXISTS `recipeinstructions`;
CREATE TABLE `recipeinstructions` (
  `id` int(55) UNSIGNED NOT NULL,
  `recipeId` int(55) NOT NULL,
  `instructions` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `recipeinstructions`
--

INSERT INTO `recipeinstructions` (`id`, `recipeId`, `instructions`) VALUES
(1, 1, 'Sprinkle chicken strips generously with paprika, sea salt and pepper. Heat skillet on high heat for 60 seconds, when hot add 2-3 tablespoons olive oil (enough to coat bottom of pan) Allow oil 30 seconds to heat.\n\nAdd chicken strips to pan, cooking 4 minutes a side or until golden brown but not cooked through. While chicken cooks, prep vegetables: -Peel and cut onion, potatoes and carrots. When chicken is golden but not cooked through, set on a plate, set aside.\n\nIf needed add more oil to pan, turn heat to medium, add onions and cook for 2-3 minutes. Add potatoes and carrots. Sprinkle with sea salt and pepper. Cook, stirring frequently for 10-12 minutes, until veggies begin to soften and edges turn golden.\n\nAdd flour and stir for one minute. Then add wine, broth and chicken. Turn heat up and bring to a simmer. -Once simmering, turn heat down (low but still simmering), cover and cook for 10-12 more minutes, or until chicken is cooked through and veggies are soft enough to easily poke with a fork but still a little firm. While chicken is cooking, prepare thyme and parsley. \n\nAdd thyme to pan a few minutes before chicken is done. \n\nremove from heat, garnish with parsley, serve.'),
(2, 2, 'Place chicken pieces in a saucepan. Add fusilli, onions, celery, and carrots, ketchup, thyme, salt, and cayenne pepper. Pour chicken broth into pan.\n\nPlace pan over medium-high heat and bring to a simmer. Reduce heat to medium-low and cook until vegetables soften and pasta is thoroughly cooked, stirring occasionally, 25 to 35 minutes. Stir in parsley before serving.'),
(3, 3, 'In a small mixing bowl whisk together honey, brown sugar, sesame oil, lime juice, soy sauce and water. Set aside.\r\n\r\nPreheat a 12 to 14-inch non-stick skillet over moderately high heat. Crumble beef into about 1-inch pieces into skillet, leaving a little space between as possible.\r\n\r\nLet beef cook undisturbed for 2 1/2 - 3 minutes until nicely browned on bottom. Sprinkle in green onions (white/light portion), garlic and ginger.\r\n\r\nToss and break up beef and continue to cook until beef if fully browned and cooked through, about 2 - 3 minutes longer. \r\n\r\nPour in honey mixture. Reduce heat to medium, then let simmer, stirring frequently, 1 minute.\r\n\r\nServe warm over rice, sprinkle with green onions, peanuts, sesame seeds and drizzle with hot sauce if desired. Serve with veggies on the side. '),
(4, 4, 'Season salmon fillets with lemon pepper, garlic powder, and salt.\r\n\r\nIn a small bowl, stir together soy sauce, brown sugar, water, and vegetable oil until sugar is dissolved. Place fish in a large resealable plastic bag with the soy sauce mixture, seal, and turn to coat. Refrigerate for at least 2 hours.\r\n\r\nPreheat grill for medium heat.\r\n\r\nLightly oil grill grate. Place salmon on the preheated grill, and discard marinade. Cook salmon for 6 to 8 minutes per side, or until the fish flakes easily with a fork.'),
(5, 5, 'Preheat oven to 400 degrees F (200 degrees C).\r\n\r\nFill a large pot with lightly salted water and bring to a rolling boil over high heat. Once the water is boiling, stir in the macaroni, and return to a boil. Cook the pasta uncovered, stirring occasionally, until the pasta is cooked through but still slightly firm, about 8 minutes. Drain well.\r\n\r\nMelt 1/4 cup butter in a large saucepan over medium heat. When the butter starts to foam and bubble, stir in the flour; cook on medium heat until flour just begins to turn pale yellow, 3 to 4 minutes. Add thyme, cayenne pepper, and white pepper; cook and stir another minute, then whisk in 1 cup of milk until smooth. Pour in remaining milk and whisk again. Bring the sauce just to a simmer.\r\n\r\nStir in nutmeg, Worcestershire sauce, and salt; simmer on medium-low heat until thickened, about 8 minutes, whisking often. Turn heat off, then add 2 1/4 cups of Cheddar cheese; stir until melted and combined. Add Dijon mustard.\r\n\r\nTransfer the macaroni into a casserole dish, then pour in the cheese sauce; stir to thoroughly combine sauce with pasta. Mix panko bread crumbs and 1 tablespoon melted butter in a small bowl, and sprinkle crumbs on top of macaroni and cheese. Sprinkle remaining 3/4 cup of Cheddar cheese on top.\r\n\r\nBake in the preheated oven until bread crumbs and Cheddar cheese topping are golden brown, about 20 minutes.'),
(6, 6, 'Preheat oven to 450 degrees F (250 degrees C).\r\n\r\nPlace potatoes in a large roasting pan and toss with oil, salt, pepper, and rosemary until evenly coated. Spread out potatoes in a single layer.\r\n\r\nBake in preheated oven for 20 minutes, stirring occasionally. Serve immediately.'),
(7, 7, 'Bring a large pot of salted water to a boil. Add potatoes and cook until tender but still firm, about 15 minutes; drain and chop.\r\n\r\nPlace eggs in a saucepan and cover with cold water. Bring water to a boil; cover, remove from heat, and let eggs stand in hot water for 10 to 12 minutes. Remove from hot water; peel and chop.\r\n\r\nIn a large bowl, combine the potatoes, eggs, celery, sweet relish, garlic, mustard, mayonnaise and salt and pepper. Gently mix together and serve warm.'),
(8, 8, 'Preheat oven to 325 degrees F (165 degrees C).\r\n\r\nArrange thinly sliced potatoes in a 9x13-inch baking dish.\r\n\r\nLayer butter slices on top of potatoes. Season with salt and black pepper.\r\n\r\nPour half-and-half evenly over potato mixture.\r\n\r\nBake in preheated oven until sauce has thickened and potatoes are tender, 45 to 60 minutes.'),
(9, 9, 'Preheat a large heavy skillet over medium heat for 3 minutes.\r\n\r\nCoat salmon with olive oil. Place in skillet, and increase heat to high. Cook for 3 minutes. Sprinkle with capers, and salt and pepper. Turn salmon over, and cook for 5 minutes, or until browned. Salmon is done when it flakes easily with a fork.\r\n\r\nTransfer salmon to individual plates, and garnish with lemon slices.'),
(10, 10, 'Preheat oven to 450 degrees. Spray a rimmed 18 by 13-inch, preferrably dark, baking sheet with non-stick cooking spray. \r\n\r\nPlace chicken on upper half of the baking sheet then place potatoes and carrots on lower half. \r\n\r\nDrizzle everything with olive oil and toss (keeping both chicken and veggies separate. I know they aren\'t in the photos, I just moved them after roasting).\r\n \r\nSeason everything with onion powder, garlic powder, paprika, salt and pepper and toss veggies.\r\n\r\nTurn chicken and season opposite side with salt and pepper.\r\n\r\nRoast in preheated oven until chicken is cooked through and veggies are tender, about 25 - 28 minutes, while tossing veggies during the last 8 minutes if needed (I didn\'t need to toss mine but the were a shade away from being too dark on bottom so you may need to toss).\r\n\r\n'),
(11, 11, 'Whisk soy sauce, honey, ginger, and garlic together in a bowl until marinade is evenly mixed. Set aside 1/4 of the marinade.\r\n\r\nPlace salmon fillets in shallow dish; pour the remaining marinade over the salmon. Cover dish with plastic wrap and refrigerate for 5 minutes.\r\n\r\nHeat sesame oil in a large skillet over medium-high heat.\r\n\r\nRemove salmon from marinade, shaking to remove excess marinade, and place, skin-side up, into the hot oil; cook for 4 minutes. Discard unused marinade in the shallow dish. Flip salmon and drizzle the reserved 1/4 of the marinade over salmon; sprinkle with sesame seeds. Cook until fish flakes easily with a fork, 5 to 7 minutes. Flip salmon, remove skin, and cook 1 minute more.'),
(12, 12, 'Preheat oven to 350 degrees F (175 degrees C). Grease a baking dish lightly with cooking spray.\r\n\r\nPlace salmon fillets in the baking dish.\r\n\r\nMix lemon juice, orange juice, lime juice, butter, parsley, paprika, salt, and pepper together until well blended. Drizzle over salmon in the baking dish.\r\n\r\nBake salmon in the preheated oven until easily flaked with a fork, 10 to 15 minutes. An instant-read thermometer inserted into the center should read 145 degrees F (63 degrees C).'),
(13, 13, 'Place salmon fillets on a baking sheet and season with salt and black pepper.\r\n\r\nCombine pecans, maple syrup, vinegar, paprika, chipotle powder, and onion powder in a food processor; pulse until texture is crumbly. Spoon pecan mixture on top of each salmon fillet, coating the entire top surface. Refrigerate coated salmon, uncovered, for 2 to 3 hours.\r\n\r\nPreheat oven to 425 degrees F (220 degrees C).\r\n\r\nBake salmon in the preheated oven until fish flakes easily with a fork, 12 to 14 minutes.'),
(14, 14, 'Heat the butter and olive oil in a large skillet over medium heat. Place salmon in the skillet, and season with garlic, lemon pepper and salt. Pour 1/4 cup water around salmon. Place tomatoes and cilantro in the skillet. Cover, and cook 15 minutes, or until fish is easily flaked with a fork.\r\n\r\nBring 2 cups water to boil in a pot. Remove form heat, and mix in couscous. Cover, and let sit 5 minutes. Serve the cooked salmon over couscous, and drizzle with sauce from skillet.'),
(15, 15, 'Preheat oven to 400 degrees F (200 degrees C). Line a shallow baking pan with aluminum foil.\r\n\r\nPlace salmon skin-side down on foil. Spread a thin layer of mustard on the top of each fillet, and season with salt and pepper. Top with bread crumbs, then drizzle with melted butter.\r\n\r\nBake in a preheated oven for 15 minutes, or until salmon flakes easily with a fork.'),
(16, 16, 'Place salmon filets in a medium, nonporous glass dish. In a separate medium bowl, combine the peanut oil, soy sauce, vinegar, green onions, brown sugar, garlic, ginger, red pepper flakes, sesame oil and salt. Whisk together well, and pour over the fish. Cover and marinate the fish in the refrigerator for 4 to 6 hours.\r\n\r\nPrepare an outdoor grill with coals about 5 inches from the grate, and lightly oil the grate.\r\n\r\nGrill the fillets 5 inches from coals for 10 minutes per inch of thickness, measured at the thickest part, or until fish just flakes with a fork. Turn over halfway through cooking.'),
(17, 17, 'Place the beef in a shallow dish. Combine soy sauce, sugar, green onion, garlic, sesame seeds, sesame oil, and ground black pepper in a small bowl. Pour over beef. Cover and refrigerate for at least 1 hour or overnight.\r\n\r\nPreheat an outdoor grill for high heat, and lightly oil the grate.\r\n\r\nQuickly grill beef on hot grill until slightly charred and cooked through, 1 to 2 minutes per side.'),
(18, 18, 'Preheat oven to 275 degrees F (135 degrees C).\r\n\r\nDiscard any flavoring packet from corned beef. Brush brisket with browning sauce on both sides. Heat vegetable oil in a large skillet over medium-high heat and brown brisket on both sides in the hot oil, 5 to 8 minutes per side.\r\n\r\nPlace brisket on a rack set in a roasting pan. Scatter onion and garlic slices over brisket and add water to roasting pan. Cover pan tightly with aluminum foil.\r\n\r\nRoast in the preheated oven until meat is tender, about 6 hours.'),
(19, 19, 'Cook and stir bacon in a heavy skillet over medium-high heat until bacon is browned and crisp, 3 to 4 minutes. Turn off heat and transfer bacon into a large stew pot, reserving bacon fat in the skillet.\r\n\r\nSeason beef chuck cubes generously with 1 teaspoon salt and black pepper to taste. Turn heat to high under skillet and sear beef pieces in the hot fat on both sides until browned, about 5 minutes. Place beef in stew pot with bacon, leaving fat in skillet. Turn heat down to medium; cook and stir onions in the retained fat in the skillet until lightly browned, 5 to 8 minutes; season with a large pinch of salt.\r\n\r\nCook garlic with onions until soft, about 1 minute; pour beer into skillet and stir with a wooden spoon, scraping up and dissolving any browned bits of food into the liquid. Pour cooking liquid from skillet into the stew pot. Stir in tomato paste, thyme sprigs, carrots, celery, sugar, 1/2 teaspoon black pepper, and enough chicken broth to cover.\r\n\r\nBring stew to a gentle simmer, stirring to combine; reduce heat to low and cover pot. Simmer stew until beef is fork-tender, about 2 hours. Stir stew occasionally and skim fat or foam if desired.\r\n\r\nRemove cover and raise heat to medium-high. Bring stew to a low boil and cook until stew has slightly thickened, 15 to 20 minutes. Remove and discard thyme sprigs and adjust salt and pepper to taste.\r\n\r\nArrange mashed potatoes in a ring in a serving bowl; ladle stew into the center of the potatoes.'),
(20, 20, 'Preheat the oven to 275 degrees F (135 degrees C).\r\n\r\nPour vegetable oil into a large oven-safe pot over medium-high heat. Season the chuck roast with salt and black pepper. Brown the meat on both sides in the hot oil, and transfer to a plate.\r\n\r\nStir carrots, celery, and onion into the pot, and cook and stir until vegetables start to release their juices, about 3 minutes; loosen any brown flavor bits on the bottom of the pot. Add butter, and cook until the onions are translucent, about 5 minutes. Then sprinkle in rosemary, stir the vegetables, and return the roast to the pot. Cover the pot with a lid.\r\n\r\nRoast in the preheated oven until the chuck roast is tender, about 2 1/2 to 3 hours. Season vegetables with additional salt and black pepper, if desired.'),
(21, 21, 'Combine porcini mushrooms and water in a bowl; soak until soft, 1 hour. Drain and reserve liquid. Dice and set mushrooms and reserved liquid aside.\r\n\r\nPreheat oven to 325 degrees F (165 degrees C).\r\n\r\nSeason beef generously with salt and pepper. Heat vegetable oil in a large ovenproof skillet over high heat. Place beef in the skillet; cook until brown on all sides, 5 to 8 minutes per side.\r\n\r\nReduce heat to medium and stir in 1 tablespoon butter, shallots, and a pinch of salt; cook until shallots are soft and translucent, 5 to 7 minutes.\r\n\r\nPour tarragon vinegar into the skillet and bring to a boil while scraping any browned bits off of the bottom. Stir until liquid is reduced by half, 2 to 4 minutes.\r\n\r\nPour in veal stock, cream, 1/2 cup reserved mushroom liquid, mushrooms, salt, and pepper; stir to combine. Return beef to the skillet.\r\n\r\nRoast in the preheated oven until meat is medium rare, about 45 minutes. An instant-read thermometer inserted into the center should read 130 degrees F (54 degrees C). Transfer meat to a plate and loosely tent with foil. Set skillet over high heat and bring pan juices to a boil.\r\n\r\nStir in 1 tablespoon butter and tarragon; season with salt and pepper to taste. Return tenderloin and any accumulated juices to skillet and serve.'),
(22, 22, 'Combine ground beef, onion, garlic, and green pepper in a large saucepan. Cook and stir until meat is brown and vegetables are tender. Drain grease.\r\n\r\nStir diced tomatoes, tomato sauce, and tomato paste into the pan. Season with oregano, basil, salt, and pepper. Simmer spaghetti sauce for 1 hour, stirring occasionally.'),
(23, 23, 'Place cumin seeds into a small skillet over medium heat; stir constantly until seeds turn dark brown and smell toasted, about 1 minute. Immediately pour seeds into a bowl to stop the cooking. Mix cumin seeds with orange juice, vegetable oil, steak seasoning, lime juice, and oregano in a bowl.\r\n\r\nPlace steaks into a large resealable plastic bag, pour orange juice marinade over the meat, and squeeze out air. Seal bag and turn it over several times to coat meat with marinade. Refrigerate at least 30 minutes, or longer for extra flavor.\r\n\r\nPreheat an outdoor grill for medium-high heat and lightly oil the grate.\r\n\r\nRemove steaks from marinade, shaking off any excess. Discard used marinade. Grill steaks on the preheated grill until seared on the outsides and still slightly pink in the centers, 6 to 8 minutes per side. An instant-read meat thermometer inserted sideways into the center of the thickest steak should read 145 degrees F (65 degrees C). Let steaks rest for 3 minutes before slicing.'),
(24, 24, 'Remove all silver skin and extra fat from the steak. Carefully cut out the connective tissue that connects the 2 halves of the steak, separating the whole into 2 long pieces. Cut lobe of meat from one half (it\'s a piece that is slightly separated from the larger half). Then cut each of the 2 larger halves into 2 steaks each. Sprinkle with salt and pepper.\r\n\r\nHeat skillet over high heat. Add clarified butter when pan is hot, then place the steaks in the pan. Reduce heat to medium. Cook until browned on all sides, firm, and reddish-pink on the inside. An instant-read thermometer inserted into the center should read 125 degrees F (52 degrees C), a total of about 12 minutes. (This cut of meat has a sort of triangular shape, so about 4 minutes per side.) Transfer to a warm plate and tent with foil to let steaks rest and allow temperature to rise to 130 degrees F.\r\n\r\nPour stock into skillet set over medium heat. Stir with a wooden spoon scraping up the browned bits from the bottom. When brownings dissolve and liquid begins to reduce after 2 or 3 minutes, reduce heat to low. Add accumulated juices from the meat, balsamic vinegar, and butter chunks. Cook and stir until butter melts. If liquid has reduced too much, add a splash of broth. Taste to check if sauce needs a bit of salt.\r\n\r\nTo serve, slice steaks and spoon pan sauce over them.\r\n'),
(25, 25, 'Combine 1/2 cup chopped fresh rosemary, garlic, 1/3 cup olive oil, 1/4 cup lemon juice, black pepper, 1/2 teaspoon red pepper flakes, and 1/2 teaspoon salt in a blender or food processor. Blend until smooth and set marinade aside.\r\n\r\nPierce the steak with a fork 20 to 30 times. Place in a shallow baking dish. Pour marinade over steak and flip to coat both sides. Cover and refrigerate for 4 to 8 hours.\r\n\r\nCombine 1/3 cup olive oil, 3 tablespoons lemon juice, lemon zest, 1 teaspoon minced rosemary, 1/8 teaspoon red pepper flakes, and a pinch of salt in a jar. Cover and shake the dressing to combine. Shake again before using.\r\n\r\nPreheat an outdoor grill for medium-high heat and lightly oil the grate.\r\n\r\nRemove steak from marinade; scrape off any chunks of marinade. Discard used marinade. Season steak with salt and black pepper.\r\n\r\nPlace steak on the preheated grill and cook until browned on the outside and red on the inside, about 6 to 8 minutes per side. Place 2 tablespoons of the olive oil-lemon juice dressing in a small bowl. Use rosemary sprig to baste the steak while it cooks. An instant-read thermometer inserted into the center of a steak should read 125 degrees F (52 degrees C) for rare.\r\n\r\nRemove steak to a platter and allow to rest about 6 minutes before slicing. Cut in half lengthwise, then into 1/4-inch-thick slices at an angle against the grain. Drizzle with additional dressing.'),
(26, 26, 'Fill a large Dutch oven about 2/3 full with water. Bring water to 130 degrees F (54 degrees C) over medium heat. Attach a candy/oil thermometer to the side of the Dutch oven in order to monitor and maintain the water temperature.\r\n\r\nGenerously season steaks with salt and black pepper. Heat vegetable oil in a large skillet over high heat. Place steaks in skillet and cook until just browned, 1 minute per side. Transfer steaks to a resealable plastic bag, squeeze out all air, and seal.\r\n\r\nPlace plastic bag containing steaks in the Dutch oven, adjusting the heat as necessary to maintain the temperature at 130 degrees F (54 degrees C). Cook for 2 1/2 hours, moving the bag around occasionally and maintaining the temperature.\r\n\r\nWhile the steaks are cooking, heat 1 tablespoon butter in the skillet over medium-low heat. Add mushrooms; cook, stirring, until mushrooms are soft, 5 minutes. Transfer to a plate and set aside.\r\n\r\nRemove steaks from plastic bag (reserving any accumulated juices) and pat dry. Generously season with salt and pepper. Heat 1 teaspoon vegetable oil in the skillet over high heat. Place steaks in skillet and cook to form a crust, 2 minutes per side. Transfer steaks to a plate.\r\n\r\nStir garlic and reserved mushrooms into skillet, reduce heat to medium, and cook until mushrooms are reheated, 2 minutes. Stir in reserved juices, water, and balsamic vinegar. Remove from heat.\r\n\r\nStir in 1 tablespoon cold butter until completely melted and incorporated. Season with salt and pepper to taste. Spoon sauce over steaks and serve.'),
(27, 27, 'Sprinkle beef strips with fajita seasoning. Saute beef in oil in large nonstick skillet over medium-high heat 3 to 4 minutes.\r\n\r\nAdd peppers and onion and saute 2 to 3 minutes longer or until vegetables are tender-crisp.\r\n\r\nDivide lettuce on 2 large plates. Spoon beef mixture over lettuce and arrange tomatoes, beans, olives and cheese over each. Serve with Southwest Fiesta Dressing, to taste. Refrigerate leftovers.'),
(28, 28, 'Heat olive oil in a skillet over medium heat. Cook onion, bell peppers, and garlic in oil until tender-crisp, stirring frequently. Set aside.\r\n\r\nHeat a large skillet over medium-high heat. Pour soy sauce, honey, and red wine vinegar in pan, then add beef. Cook beef, stirring frequently, until done, about 10 to 15 minutes. Stir in cooked vegetables, and cook another 10 to 15 minutes.'),
(29, 29, 'Preheat oven to 450 degrees F (230 degrees C). Move oven rack to the center position.\r\n\r\nIn a large bowl, combine bread crumbs, garlic, rosemary, 1 teaspoon salt and 1/4 teaspoon pepper. Toss in 2 tablespoons olive oil to moisten mixture. Set aside.\r\n\r\nSeason the rack all over with salt and pepper. Heat 2 tablespoons olive oil in a large heavy oven proof skillet over high heat. Sear rack of lamb for 1 to 2 minutes on all sides. Set aside for a few minutes. Brush rack of lamb with the mustard. Roll in the bread crumb mixture until evenly coated. Cover the ends of the bones with foil to prevent charring.\r\n\r\nArrange the rack bone side down in the skillet. Roast the lamb in preheated oven for 12 to 18 minutes, depending on the degree of doneness you want. With a meat thermometer, take a reading in the center of the meat after 10 to 12 minutes and remove the meat, or let it cook longer, to your taste. Let it rest for 5 to 7 minutes, loosely covered, before carving between the ribs.'),
(30, 30, 'Season lamb shanks with salt and pepper.\r\n\r\nHeat olive oil in a deep-sided pan or pot over medium-high heat. Add lamb and cook, turning as needed, until browned, about 5 minutes. Remove from pan and reduce heat to medium.\r\n\r\nPlace chopped onion, carrot, celery, and garlic in the pan. Season with a large pinch of salt. Cook and stir until vegetable juices start to come out, about 2 minutes. Add tomato paste and stir to coat, about 1 minute. Pour in beer and stir in rosemary. Raise heat to high and bring sauce mixture to a simmer.\r\n\r\nToss lamb shanks in with the sauce mixture. Reduce heat to low. Cover and simmer until lamb is nearly fork-tender, flipping lamb after 1 hour, about 2 hours. Remove from heat and let cool to room temperature, at least 30 minutes. Refrigerate, 8 hours to overnight.\r\n\r\nSkim the fat off the top of the sauce, if desired. Cover and bring lamb to a simmer over low heat. Flip and continue simmering until meat is fork-tender and nearly falling off the bone, about 45 minutes. Place lamb shanks in a bowl to keep warm.\r\n\r\nBring sauce to a boil over high heat. Boil until reduced by half but not too thick, about 3 minutes. Season with salt and cayenne pepper. Plate the lamb shanks and spoon sauce on top.'),
(31, 31, 'Mix together the vinegar, salt, pepper, garlic, onion, and olive oil in a large resealable bag until the salt has dissolved. Add lamb, toss until coated, and marinate in refrigerator for 2 hours.\r\n\r\nPreheat an outdoor grill for medium-high heat.\r\n\r\nRemove lamb from the marinade and leave any onions on that stick to the meat. Discard any remaining marinade. Wrap the exposed ends of the bones with aluminum foil to keep them from burning. Grill to desired doneness, about 3 minutes per side for medium. The chops may also be broiled in the oven about 5 minutes per side for medium.'),
(32, 32, 'In a medium bowl, mix brown sugar, ginger, tarragon, cinnamon, pepper, garlic powder, and salt. Rub lamb chops with the seasonings, and place on a plate. Cover, and refrigerate for 1 hour.\r\n\r\nPreheat grill for high heat.\r\n\r\nBrush grill grate lightly with oil, and arrange lamb chops on grill. Cook 5 minutes on each side, or to desired doneness.'),
(33, 33, 'Whisk yogurt, lemon juice, lemon zest, chile paste, garlic, rosemary, oregano, salt, black pepper, and cinnamon together in a small bowl. Transfer into a resealable plastic bag. Add the lamb chops, coat with the marinade, squeeze out excess air, and seal the bag. Marinate in the refrigerator for 4 hours.\r\n\r\nPreheat grill for medium heat and lightly oil the grate.\r\n\r\nRemove lamb chops from from marinade and scrape off excess. Discard used marinade. Season chops with salt and black pepper. Place on the preheated grill and cook until browned and medium rare on the inside, 3 to 4 minutes. An instant-read thermometer inserted into the center should read 130 degrees F (54 degrees C).'),
(34, 34, 'Place the yogurt, water, lemon juice, vinegar, olive oil, onion, and garlic into a large mixing bowl. Whisk in the salt, black pepper, cumin, nutmeg, clove, mace, and cayenne pepper until evenly blended. Mix in the lamb strips to coat. Cover the bowl with plastic wrap, and marinate in the refrigerator 12 to 24 hours (the longer the better).\r\n\r\nHeat a large skillet over high heat. Cook the lamb strips in a single layer in batches until the fat melts and the meat has browned and is no longer pink on the inside, about 5 minutes, turning occasionally.'),
(35, 35, 'Preheat the oven to 325 degrees F (165 degrees C).\r\n\r\nPuncture the leg of lamb with the tip of a knife just far enough to insert slivers of garlic into the holes. Mix together the dill, salt and rosemary, and rub over the leg of lamb. Place the lamb, fatty side up, on a rack in a shallow roasting pan.\r\n\r\nRoast uncovered for 2 to 2 1/2 hours in the preheated oven, to an internal temperature of 155 degrees F (68 degrees C) for medium. Tent with aluminum foil and let stand for 15 to 20 minutes before carving. The lamb will continue to cook a little bit, and the juices will set up better for carving.'),
(36, 36, 'Place the lamb chops into a roasting pan, and season evenly with the garlic, garlic powder, chili powder, sugar, salt, and pepper. Drizzle with 1 tablespoon of lime juice, soy sauce and olive oil. Cover and refrigerate overnight.\r\n\r\nPreheat the oven to 400 degrees F (200 degrees C). Allow the lamb to stand at room temperature while the oven preheats.\r\n\r\nRoast uncovered in the preheated oven to your desired degree of doneness, about 20 minutes for medium, or 30 minutes for well done. Garnish with a sprinkle of cilantro and squeeze lemon and lime juice over the top before serving.'),
(37, 37, 'Season both sides of skirt steak with carne asada seasoning. Refrigerate at least 30 minutes.\r\n\r\nPreheat an outdoor grill for medium-high heat and lightly oil the grate. Cook steak until each side is seared, 6 to 8 minutes per side or to desired doneness. An instant-read thermometer inserted into the center should read 150 degrees F (65 degrees C). Transfer to a plate and let rest 10 minutes before slicing into thin slices and then into small chunks. Keep warm.\r\n\r\nBake steak fries according to package directions.\r\n\r\nCombine tomatoes, onions, cilantro, and red pepper flakes in a mixing bowl.\r\n\r\nMelt butter in a skillet over medium heat. Crack eggs into skillet and cook to desired doneness.\r\n\r\nDivide fries among 4 serving places. Top with carne asada, some of the tomato-onion mixture, shredded cheese, egg, and guacamole.'),
(38, 38, 'Place sliced meat into a shallow bowl, and season with salt, black pepper, and crushed red pepper. Squeeze the lime juice over the meat, and turn until evenly coated. Cover, and refrigerate for 30 minutes.\r\n\r\nIn a blender or food processor, combine tomatillo and jalapeno. Puree for 15 to 20 seconds, or until thick. Heat 1 tablespoon oil in a large skillet over medium high heat. Carefully pour in tomatillo mixture. Cook, stirring frequently, for 5 minutes. Stir in beef broth. Reduce heat, and simmer for 20 to 30 minutes, or until mixture coats a spoon. Transfer mixture to a serving dish.\r\n\r\nHeat tablespoon oil in a large skillet over high heat. Stir in 1/3 of the beef, and saute for 1 minute. Transfer to serving dish. Repeat with remaining beef. Meanwhile, heat tortillas in the oven or microwave, according to package instructions.\r\n\r\nTo serve, place two tortillas on top of each other. Add desired amount of meat, spoon over some tomatillo mixture. Top with onions, tomatoes, avocado and cilantro. Garnish with a wedge of lemon, to be squeezed over taco before eating.'),
(39, 39, 'Place beef slices in a mixing bowl. Sprinkle with asada seasoning and garlic powder; toss in bowl to evenly coat. Let marinade 5 minutes.\r\n\r\nHeat oil in a large, deep skillet over medium-high heat. Place beef strips in skillet and cook and stir until browned. Stir in bell pepper, onions, and jalapeno pepper. Add tomatoes and potatoes. Cook mixture until potatoes are tender, 5 to 8 minutes. Season with salt and pepper. Transfer mixture to a bowl.\r\n\r\nMelt 1 tablespoon butter in the same skillet. Add the eggs, stirring occasionally, until eggs are scrambled and set. Transfer the beef mixture back to skillet. Cook and stir until warmed through, about 2 minutes. Melt the remaining 2 tablespoons butter in a small dish in microwave.\r\n\r\nDivide shredded cheese among tortillas; divide beef and veggie mixture and place on the cheese. Fold in sides of tortilla and roll up. Brush with melted butter and place folded side down in pan to brown; flip and brown on top side. Burrito should be warmed though.'),
(40, 40, 'Combine onion, soy sauce, lime juice, lemon juice, orange juice, cilantro, chili powder, garlic, cumin, oregano, coriander, hot sauce, chipotle pepper, black pepper, and sugar in a 1-gallon plastic zip-top bag. Add steak and seal. Marinate in the refrigerator, turning and massaging meat frequently, for up to 24 hours.\r\n\r\nHeat olive oil in a large frying pan over high heat. Add steak and marinade. Cook steak until medium-rare to medium, 4 to 5 minutes per side. An instant-read thermometer inserted into the center should read 130 to 140 degrees F (54 to 60 degrees C).'),
(41, 41, 'Season chuck steaks on both sides with chili powder, onion powder, cumin, garlic powder, salt, and black pepper.\r\n\r\nHeat 2 tablespoons vegetable oil in a large skillet over medium-high heat. Cook chuck steaks in the hot oil in batches until browned, about 5 minutes per side. Transfer to a slow cooker.\r\n\r\nHeat remaining 1 1/2 teaspoon vegetable oil in the same skillet. Add 2 green onions and garlic; cook and stir until browned but not burnt, 3 to 4 minutes. Remove from heat; chop garlic coarsely and return to the skillet.\r\n\r\nWhisk tequila, lime juice, lemon juice, orange juice, and ginger together in a bowl. Mash in kiwi using a fork. Stir in green onion-garlic mixture and chipotle sauce. Pour over chuck steaks in the slow cooker.\r\n\r\nCook on Low until steaks are fork-tender, 6 to 8 hours.\r\n\r\nTransfer chuck steaks to a cutting board; shred with 2 forks. Mix in 2 raw green onions.\r\n\r\nPour cooking liquid from the slow cooker into the skillet. Simmer over medium heat until reduced and thickened into a sauce, about 10 minutes. Stir in shredded steak; simmer until most of the sauce is absorbed, about 5 minutes.\r\n\r\nPreheat oven to 350 degrees F (175 degrees C). Coat the bottom of a 9x13-inch baking dish with 1/4 of the pasilla chile sauce.\r\n\r\nSpoon shredded steak mixture into tortillas. Wrap up and place seam-side down, close together, in the baking dish. Pour remaining pasilla chile sauce over tortillas. Sprinkle mozzarella cheese and chives on top.\r\n\r\nBake in the preheated oven until cheese is melted and bubbly, 20 to 30 minutes.'),
(42, 42, 'Combine jalapeno, garlic, kosher salt, and 1 teaspoon black pepper in a mortar. Grind into a paste.\r\n\r\nPour lime juice, orange juice, and vinegar into a glass bottle or lidded container; add garlic mixture and shake well. Place steak in a shallow bowl and pour marinade over. Cover with plastic wrap and refrigerate until steak absorbs flavors, 4 to 6 hours.\r\n\r\nPreheat grill for medium heat and lightly oil the grate.\r\n\r\nRemove steak from the marinade and place on a cutting board. Season with salt and pepper and slice against the grain into thin strips.\r\n\r\nGrill until slightly charred and light pink in the center, about 5 minutes per side.'),
(43, 43, 'Place beef chuck in a shallow bowl. Season with pepper, salt, and red pepper flakes. Add enough beef stock to cover. Add lemon juice, lime juice, jalapenos, and cilantro. Turn until evenly coated. Cover and refrigerate for at least 30 minutes, preferably 2 to 3 hours.\r\n\r\nHeat oil in a large skillet over high heat. Stir in 1/3 of the beef and saute until just firm to the touch for medium- to medium-rare, 1 to 2 minutes per side. Be careful not to overcook, as the meat will get tough. Transfer to serving dish. Repeat with remaining beef.'),
(44, 44, 'Preheat oven to 350 degrees F (175 degrees C).\r\n\r\nPrepare the elbow macaroni according to package directions.\r\n\r\nMeanwhile, melt the butter in a small saucepan over medium high heat. Stir in the flour until a cream colored paste forms. Then pour in the milk and stir constantly until this comes to a hard boil, then stir for 1 more minute. Remove from heat and set aside.\r\n\r\nWhen the macaroni is cooked, spread 1/2 of it into the bottom of a lightly greased 9x13-inch baking dish. Then layer 1/2 of the grated onion, 1/2 of the salt and pepper and 1/2 of each of the cheeses. Repeat this one more time: macaroni, onion, salt and pepper and cheeses, and then pour the reserved white sauce over all. Top off with small pats of butter to taste.\r\n\r\nCover and bake at 350 degrees F (175 degrees C) for 45 minutes.'),
(45, 45, 'Preheat oven to 350F (175C) and lightly grease a 1.5qt round baking dish or 9x9 square baking dish with butter.\r\n\r\nCook pasta al dente according to package instructions.\r\n\r\nMeanwhile, melt butter in a large pot over medium heat. Once it has melted, add flour and stir until smooth.\r\n\r\nAdd milk and spices (salt, pepper, garlic powder, onion powder, and ground mustard), stir well and bring to a boil.\r\n\r\nOnce mixture begins to boil, reduce heat, bring to a simmer, and stir frequently until it is slightly thickened.\r\n\r\nReduce heat to low and add cream cheese, mozzarella cheese, cheddar cheese, and sour cream. Stir until cheeses are melted and mixture is smooth.\r\n\r\nAdd hot sauce and stir.\r\n\r\nAdd shredded chicken and cooked, drained pasta noodles and stir until well coated by the sauce.\r\n\r\nPour into prepared baking dish and prepare your Panko topping.'),
(46, 46, 'Cook pasta in a large pot of boiling salted water until al dente. Drain.\r\n\r\nMix together condensed soup and cheese. Using the empty soup can, measure 1 can of milk; mix into the soup mixture. Stir in cooked pasta. Dump into a greased casserole dish, and cover.\r\n\r\nBake at 325 degrees F (165 degrees C) for 45 minutes.'),
(47, 47, 'Fill a pot with lightly salted water and bring to a rolling boil over high heat. Stir in the macaroni, and return to a boil. Cook, uncovered, stirring occasionally, until the macaroni is cooked through but still firm to the bite, about 7 minutes. Drain. Stir in the 2 tablespoons butter, the 1/4 cup milk, and the cheese packet from the package.\r\n\r\nWhile the macaroni is still hot, stir in the Cheddar cheese, pimento cheese spread, and Italian cheese blend, and continue to stir until melted. Place the macaroni and cheese mixture in a container and refrigerate until firm, about 4 hours.\r\n\r\nLine a baking sheet with parchment paper. Remove the macaroni mixture from the refrigerator, and, using a cookie scoop, scoop into balls. Place mac balls on the prepared baking sheet and freeze for at least 2 hours.\r\n\r\nHeat oil in a deep fryer or large saucepan to 350 degrees F (175 degrees C).\r\n\r\nWhisk the bread crumbs with the paprika, chili powder, black pepper, sugar, and cayenne in a shallow dish; set aside. Beat the eggs with the 3 tablespoons milk in a small bowl. Remove the mac balls from the freezer, coat in the egg wash, and then dredge in breading.\r\n\r\nFry the mac balls in small batches until golden brown, 3 to 5 minutes. Drain briefly on a paper towel-lined plate; serve hot.'),
(48, 48, 'Mix salt, dry mustard, garlic powder, paprika, onion powder, white pepper, and black pepper in a small bowl.\r\n\r\nBring a large pot of lightly salted water to a boil. Cook elbow macaroni in the boiling water, stirring occasionally until cooked through but firm to the bite, 8 minutes. Drain and rinse macaroni under cold water until cooled.\r\n\r\nWhisk mayonnaise, sour cream, and evaporated milk in a large salad bowl until dressing is smooth and creamy; stir in seasoning mix until well blended. Mix macaroni, onion, green, red, and yellow bell pepper, celery, and carrots into the dressing until thoroughly coated.'),
(49, 49, 'Cook bacon in a large, deep skillet over medium-high heat until crisp, about 10 minutes; drain on a plate lined with paper towels until cool. Crumble the bacon.\r\n\r\nBring a large pot of lightly salted water to a boil. Cook elbow macaroni in the boiling water, stirring occasionally, until cooked through but firm to the bite, 8 minutes; drain.\r\n\r\nRinse macaroni with cold water until cool; drain.\r\n\r\nMix cooled macaroni, crumbled bacon, mayonnaise, red onion, green bell pepper, ranch salad dressing mix, and Cheddar cheese together in a large bowl.\r\n\r\nCover the bowl with plastic wrap and refrigerate at least 4 hours before serving.'),
(50, 50, 'Bring a large pot of salted water to a boil, add the macaroni and let it cook until al dente; drain well.\r\n\r\nIn a medium-size mixing bowl, combine onion, bell pepper, celery, mayonnaise, sweet pickle relish, ketchup, pickle juices, horseradish, hot pepper sauce, parsley, celery seed, chili powder, salt, black pepper and shrimp. Fold the macaroni into the mixture. Cover and chill at least 3 hours before serving.');

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

DROP TABLE IF EXISTS `recipes`;
CREATE TABLE `recipes` (
  `id` int(10) UNSIGNED NOT NULL,
  `title` varchar(255) NOT NULL,
  `ingredients` longtext NOT NULL,
  `image` longtext NOT NULL,
  `timeToCook` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`id`, `title`, `ingredients`, `image`, `timeToCook`) VALUES
(1, 'Braised Chicken with Steamed Veggies', 'Chicken', 'braisedchickenwithsteamedveggies.png', '00:50'),
(2, 'Chicken Noodle Soup', 'Chicken', 'herbedchickenwithroastedveggies.png', '00:50'),
(3, 'Beef w/ Rice', 'Beef', 'beefwithrice.jpg', '00:40'),
(4, 'Grilled Salmon', 'Salmon', 'grilledsalmon.jpg', '00:35'),
(5, 'Chef John\'s Macaroni and Cheese', 'Macaroni', 'chefjohnsmacandcheese.jpg', '00:30'),
(6, 'Roast Potatoes', 'Potatoe', 'roastpotatoes.jpg', '00:25'),
(7, 'Southern Potatoe Salad', 'Potatoe', 'southernpotatoesalad.jpg', '00:30'),
(8, 'Old Irish Scalloped Potatoes', 'Potatoe', 'oldirishscallopedpotatoes.jpg', '00:15'),
(9, 'Pan Seared Salmon', 'Salmon', 'pansearedsalmon.jpg', '00:10'),
(10, 'Herbed Chicken with Roasted Veggies', 'Chicken', 'herbedchickenwithroastedveggies.png', '00:35'),
(11, 'Sesame Grilled Salmon', 'Salmon', 'sesamegrilledsalmon.jpg', '00:10'),
(12, 'Citrus Baked Fish', 'Salmon', 'citrusbakedfish.jpg', '00:15'),
(13, 'Paleo Pecan Maple Salmon', 'Salmon', 'paleopecanmaplesalmon.jpg', '00:15'),
(14, 'Lemon Pepper Salmon', 'Salmon', 'lemonpeppersalmon.jpg', '00:30'),
(15, 'Baked Salmon Fillets Dijon', 'Salmon', 'bakedsalmonfilletsdijon.jpg', '00:25'),
(16, 'Firecracker Grilled Alaska Salmon', 'Salmon', 'firecrackergrilledalaskasalmon.jpg', '06:40'),
(17, 'Beef Bulgolgi', 'Beef', 'beefbulgogi.jpg', '01:15'),
(18, 'Braised Corned Beef Brisket', 'Beef', 'braisedcornedbeefbrisket.jpg', '06:30'),
(19, 'Beef and Guinness Stew', 'Beef', 'beefandguinnessstew.jpg', '03:00'),
(20, 'Simple Beef Pot Roast', 'Beef', 'simplebeefpotroast.jpg', '03:30'),
(21, 'Roast Beef Tenderloin', 'Beef', 'roastbeeftenderloin.jpg', '02:20'),
(22, 'Spaghetti Sauce with Ground Beef', 'Beef', 'spaghettisaucewithgroundbeef.jpg', '01:25'),
(23, 'Cuban Marinated Steak', 'Steak', 'cubanmarinatedsteak.jpg', '01:05'),
(24, 'Butcher\'s Steak', 'Steak', 'butcherssteak.jpg', '00:50'),
(25, 'Tuscan Flank Steak', 'Steak', 'tuscanflanksteak.jpg', '04:40'),
(26, 'Sous Vide New York Strip Steak', 'Steak', 'sousvidenewyorkstripsteak.jpg', '02:55'),
(27, 'Steak Fajita Salad', 'Steak', 'steakfajitasalad.jpg', '00:35'),
(28, 'Maria\'s Pepper Steak', 'Steak', 'mariaspeppersteak.jpg', '00:50'),
(29, 'Roasted Rack of Lamb', 'Lamb', 'roastedrackoflamb.jpg', '00:40'),
(30, 'Beer Braised Lamb Shanks', 'Lamb', 'beerbraisedlambshanks.jpg', '11:55'),
(31, 'Simple Grilled Lamb Chops', 'Lamb', 'simplegrilledlambchops.jpg', '02:16'),
(32, 'Grilled Lamb with Brown Sugar Glaze', 'Lamb', 'grilledlambwithbrownsugarglaze.jpg', '01:25'),
(33, 'Grilled Lemon and Rosemary Lamb Chops', 'Lamb', 'grilledlemonandrosemarylambchops.jpg', '00:45'),
(34, 'Lamb Shwarma', 'Lamb', 'lambshwarma.jpg', '12:50'),
(35, 'Garlic and Herb Lamb', 'Lamb', 'garlicandherblamb.jpg', '02:05'),
(36, 'Vietnamese Aromatic Lamb Chops', 'Lamb', 'vietnamesearomaticlambchops.jpg', '08:30'),
(37, 'Carne Asada Breakfast Fries', 'Carne Asada', 'carneasadabreakfastfries.jpg', '01:15'),
(38, 'Carne Asada Tacos', 'Carne Asada', 'carneasadatacos.jpg', '01:15'),
(39, 'Carne Asada Breakfast Burrito', 'Carne Asada', 'carneasadabreakfastburrito.jpg', '00:50'),
(40, 'Citrus Carne Asada Marinade', 'Carne Asada', 'citruscarneasadamarinade.jpg', '24:25'),
(41, 'Carne Asada Enchiladas', 'Carne Asada', 'carneasadaenchiladas.jpg', '07:33'),
(42, 'Tacos de Carne Asada', 'Carne Asada', 'tacosdecarneasada.jpg', '04:30'),
(43, 'Sonoran Carne Asada', 'Carne Asada', 'sonorancarneasada.jpg', '01:12'),
(44, 'Old Fashioned Mac and Cheese', 'Macaroni', 'oldfashionedmacandcheese.jpg', '01:05'),
(45, 'Buffalo Chicken Mac and Cheese', 'Macaroni', 'buffalochickenmacandcheese.jpg', '00:35'),
(46, 'Simple Mac and Cheese', 'Macaroni', 'simplemacandcheese.jpg', '00:30'),
(47, 'Fried Mac and Cheese Balls', 'Macaroni', 'friedmacandcheeseballs.jpg', '07:10'),
(48, 'Creamy Macaroni Salad', 'Macaroni', 'creamymacaronisalad.jpg', '00:35'),
(49, 'Bacon Ranch Macaroni Salad', 'Macaroni', 'baconranchmacaronisalad.jpg', '04:40'),
(50, 'Moms Shrimp Macaroni Salad', 'Macaroni', 'momsshrimpmacaronisalad.jpg', '03:30');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `favoriterecipes`
--
ALTER TABLE `favoriterecipes`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `recipeinstructions`
--
ALTER TABLE `recipeinstructions`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `favoriterecipes`
--
ALTER TABLE `favoriterecipes`
  MODIFY `id` int(55) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=233;
--
-- AUTO_INCREMENT for table `recipeinstructions`
--
ALTER TABLE `recipeinstructions`
  MODIFY `id` int(55) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;
--
-- AUTO_INCREMENT for table `recipes`
--
ALTER TABLE `recipes`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
